frr defaults traditional
hostname spine
log stdout
!
interface lo
 ip address 10.200.255.2/32
!
router bgp 65100
 bgp router-id 10.200.255.2
 bgp bestpath as-path multipath-relax
 maximum-paths 8
 neighbor 10.200.1.2 remote-as 65101
 neighbor 10.200.1.2 description leaf1
 neighbor 10.200.1.2 password ${FABRIC_BGP_PASSWORD}
 neighbor 10.200.1.2 timers 3 9
 neighbor 10.200.1.2 soft-reconfiguration inbound
 neighbor 10.200.1.2 route-map FABRIC-IN in
 neighbor 10.200.1.2 route-map SPINE-OUT out
 neighbor 10.200.1.2 maximum-prefix 256
 neighbor 10.200.1.10 remote-as 65102
 neighbor 10.200.1.10 description leaf2
 neighbor 10.200.1.10 password ${FABRIC_BGP_PASSWORD}
 neighbor 10.200.1.10 timers 3 9
 neighbor 10.200.1.10 soft-reconfiguration inbound
 neighbor 10.200.1.10 route-map FABRIC-IN in
 neighbor 10.200.1.10 route-map SPINE-OUT out
 neighbor 10.200.1.10 maximum-prefix 256
 neighbor 10.200.1.19 remote-as 65000
 neighbor 10.200.1.19 description edge
 neighbor 10.200.1.19 password ${FABRIC_BGP_PASSWORD}
 neighbor 10.200.1.19 timers 3 9
 neighbor 10.200.1.19 soft-reconfiguration inbound
 neighbor 10.200.1.19 route-map FABRIC-IN in
 neighbor 10.200.1.19 route-map SPINE-OUT out
 neighbor 10.200.1.19 maximum-prefix 256
 network 10.200.255.2/32
!
ip prefix-list COMPANY seq 10 permit 10.200.0.0/16 le 32
ip prefix-list EG-VIPS seq 10 permit 10.198.0.0/24 ge 32 le 32
ip prefix-list CILIUM-VIPS seq 10 permit 10.199.0.0/24 ge 32 le 32
!
route-map FABRIC-IN permit 10
 match ip address prefix-list COMPANY
route-map FABRIC-IN permit 20
 match ip address prefix-list EG-VIPS
route-map FABRIC-IN permit 30
 match ip address prefix-list CILIUM-VIPS
!
route-map SPINE-OUT permit 10
 match ip address prefix-list COMPANY
route-map SPINE-OUT permit 20
 match ip address prefix-list EG-VIPS
route-map SPINE-OUT permit 30
 match ip address prefix-list CILIUM-VIPS
!
