#!/usr/bin/env bash
# verify.sh — run every claim this PoC makes, end to end, and print the real output.
#
# Usage:
#   scripts/verify.sh                      # print to the terminal
#   scripts/verify.sh > docs/VERIFICATION_RUN.md   # capture it as a document
#
# WHY THIS EXISTS. Every README quotes captured output, but quoted output goes stale the moment
# something changes. This script re-runs all of it in one pass, so a reader can regenerate the
# evidence on their own cluster and compare, rather than trusting a snapshot from someone else's
# laptop.
#
# It is READ-ONLY apart from the HTTP requests it makes to the demo app, which is itself a
# read-only workload. It creates nothing and deletes nothing.
#
# Exit code is always 0: this is an evidence report, not a pass/fail gate. Some commands are
# EXPECTED to fail (a curl that times out is how an L3 policy denial looks), so a non-zero exit
# would be misleading. Read the output.
set -uo pipefail

CTX="${CTX:-kind-poc1}"
# Pinned to -n default on purpose: the kubeconfig's current namespace is whatever the last person
# left it (a `kubens routes` made every un-namespaced check here report NotFound — gotcha #34).
# A later -n on a command line overrides this one, so the explicit -n kube-system etc. below still win.
K="kubectl --context $CTX -n default"

hdr() {
  echo
  echo '```'
  echo "════════════════════════════════════════════════════════════════════════════════"
  echo " $*"
  echo "════════════════════════════════════════════════════════════════════════════════"
  echo '```'
  echo
}
run() {
  echo '```console'
  echo "\$ $*"
  eval "$@" 2>&1
  rc=$?
  [ $rc -ne 0 ] && echo "[exit code: $rc]"
  echo '```'
  echo
}

echo "# Verification run"
echo
echo "Generated by \`scripts/verify.sh\` on **$(date -u +%Y-%m-%dT%H:%M:%SZ)** against context \`$CTX\`."
echo
echo "Every block below is a real command and its real output. Re-run the script to regenerate."

hdr "0. VERSIONS"
run "kind --version"
run "$K version --client -o yaml | grep gitVersion | head -1"
run "helm version --short"
run "cilium version --client | head -1"
run "hubble version"
run "docker info --format 'Mem={{.MemTotal}} CPUs={{.NCPU}} Kernel={{.KernelVersion}}'"

hdr "1. CLUSTER STATE"
run "$K get nodes -o wide"
run "$K get pods -A -o wide"

hdr "2. CILIUM STATUS"
run "$K -n kube-system exec ds/cilium -c cilium-agent -- cilium-dbg status"
echo "The \`Degraded(1)\` in Modules Health is a known kernel constraint, not a fault — see docs/FINDINGS.md:"
run "$K -n kube-system exec ds/cilium -c cilium-agent -- cilium-dbg status --all-health 2>/dev/null | grep -A2 socket-termination"

hdr "3. DEMO 03 — SERVICES WITHOUT KUBE-PROXY"
echo "Only Cilium's own DaemonSets exist — no kube-proxy:"
run "$K -n kube-system get daemonset"
echo "Zero Service iptables chains. A kube-proxy cluster would have dozens:"
run "docker exec poc1-worker sh -c 'iptables-save 2>/dev/null | grep -c KUBE-SVC || echo 0'"
echo "What is doing the load balancing instead — note entry for 10.11.0.1:443, the API itself:"
run "$K -n kube-system exec ds/cilium -c cilium-agent -- cilium-dbg service list 2>/dev/null | head -14"

hdr "4. DEMO 02 — L3/L4 vs L7 NETWORK POLICY"
run "$K get ciliumnetworkpolicy"
echo "Allowed by the L7 rule:"
run "$K exec tiefighter -- curl -s -XPOST -w '\n[http_code=%{http_code} time=%{time_total}s]\n' --max-time 8 deathstar.default.svc.cluster.local/v1/request-landing"
echo "SAME pod, SAME port, different method+path — refused at L7 with an immediate 403:"
run "$K exec tiefighter -- curl -s -XPUT -w '\n[http_code=%{http_code} time=%{time_total}s]\n' --max-time 8 deathstar.default.svc.cluster.local/v1/exhaust-port"
echo "Denied at L3/L4 instead — the SYN is dropped, so this TIMES OUT rather than returning 403:"
run "$K exec xwing -- curl -s -XPOST -w '\n[http_code=%{http_code}]\n' --max-time 6 deathstar.default.svc.cluster.local/v1/request-landing"

hdr "5. DEMO 05 — GATEWAY API + LB IPAM (no kube-vip, no MetalLB)"
SWGW=$($K get gateway sw-gateway -o jsonpath='{.status.addresses[0].value}' 2>/dev/null)
echo "sw-gateway address read live: ${SWGW:-<none>}  (pinned inside gateway-pool via spec.infrastructure.annotations)"
run "$K get ciliumloadbalancerippool -o custom-columns='NAME:.metadata.name,START:.spec.blocks[0].start,STOP:.spec.blocks[0].stop,CONFLICT:.status.conditions[?(@.type==\"cilium.io/PoolConflict\")].status'"
run "$K get gatewayclass"
run "$K get gateway,httproute"
run "$K get svc -A --field-selector spec.type=LoadBalancer"
run "$K describe ciliumloadbalancerippool kind-docker-pool | sed -n '1,20p'"
echo "Which node is announcing each address (leader-elected, like kube-vip would do):"
run "$K -n kube-system get lease | grep l2announce"
echo "Proof nothing else is installed:"
run "$K get pods -A | grep -iE 'kube-vip|metallb' || echo 'none — no kube-vip, no MetalLB'"
echo "From the macOS host, through the Gateway (needs the SETUP Step 3.5 route):"
run "curl -s -XPOST -w '\n[http_code=%{http_code} time=%{time_total}s]\n' --max-time 8 http://$SWGW/v1/request-landing"
echo "Policy still applies to Gateway traffic — the dangerous path is refused here too:"
run "curl -s -XPUT -w '\n[http_code=%{http_code} time=%{time_total}s]\n' --max-time 8 http://$SWGW/v1/exhaust-port"
run "curl -s -o /dev/null -w 'hubble-ui http://172.18.255.201/ -> [http_code=%{http_code} time=%{time_total}s]\n' --max-time 8 http://172.18.255.201/"

hdr "6. DEMO 04 — WIREGUARD TRANSPARENT ENCRYPTION"
echo "Encryption status per node — distinct pubkeys, 4 peers each:"
for n in poc1-worker poc1-worker2 poc1-control-plane poc1-control-plane2 poc1-control-plane3; do
  POD=$($K -n kube-system get pod -l k8s-app=cilium --field-selector "spec.nodeName=$n" -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)
  echo '```console'
  echo "\$ cilium-dbg status | grep Encryption   # on $n"
  $K -n kube-system exec "$POD" -c cilium-agent -- cilium-dbg status 2>/dev/null | grep -i '^Encryption' || echo "(unavailable)"
  echo '```'
  echo
done
echo "The device, and its counters — proof it is carrying real traffic:"
run "docker exec poc1-worker ip -s link show cilium_wg0"

hdr "7. DEMO 01 — HUBBLE OBSERVABILITY"
# -P opens its port-forward through the CURRENT kube context unless told otherwise, and `kind create
# cluster` changes the current context to the newest cluster (gotcha #44). Pin it, like -n default.
run "hubble status -P --kube-context $CTX \$(scripts/hubble-tls.sh $CTX) 2>&1 | grep -v level=WARN"
echo "L7 flows, with method, path, status and latency — no application instrumentation:"
run "hubble observe --last 6 -P --kube-context $CTX \$(scripts/hubble-tls.sh $CTX) --protocol http 2>&1 | grep -v level=WARN"
echo "Verdicts. Note the two shapes: 'Policy denied ... SYN' is L3/L4, 'http-request DROPPED' is L7:"
run "hubble observe --last 6 -P --kube-context $CTX \$(scripts/hubble-tls.sh $CTX) --verdict DROPPED 2>&1 | grep -v level=WARN"

hdr "8. DEMO 07 — CLUSTERMESH (needs poc2)"
if kubectl --context kind-poc2 get nodes >/dev/null 2>&1; then
  run "cilium clustermesh status --context kind-poc1 2>&1 | tail -6"
  run "cilium clustermesh status --context kind-poc2 2>&1 | tail -4"
  echo "One eBPF service entry with backends in BOTH pod CIDRs (10.10.x = poc1, 10.20.x = poc2):"
  run "$K -n kube-system exec ds/cilium -c cilium-agent -- cilium-dbg service list 2>/dev/null | grep -A4 \$($K get svc rebel-base -o jsonpath='{.spec.clusterIP}' 2>/dev/null)"
  echo "A provider that exists ONLY in poc2, reached from poc1 by an ordinary local Service name:"
  run "$K get endpoints payments 2>&1; $K exec tiefighter -- curl -s --max-time 6 http://payments.default.svc.cluster.local/"
else
  echo "_poc2 not present — ClusterMesh section skipped._"
fi

hdr "9. DEMO 08 — ENTERPRISE CA (cert-manager)"
echo "Same root fingerprint in both clusters, and mesh certs issued by it:"
run "for c in kind-poc1 kind-poc2; do printf '%-10s ' \$c; kubectl --context \$c -n cert-manager get secret clustermesh-root-ca -o jsonpath='{.data.tls\\.crt}' 2>/dev/null | base64 -d | openssl x509 -noout -fingerprint -sha256 2>/dev/null || echo '(absent)'; done"
run "for c in kind-poc1 kind-poc2; do printf '%-10s ' \$c; kubectl --context \$c -n kube-system get secret clustermesh-apiserver-server-cert -o jsonpath='{.data.tls\\.crt}' 2>/dev/null | base64 -d | openssl x509 -noout -issuer 2>/dev/null || echo '(absent)'; done"
run "$K get clusterissuer"

hdr "10. DEMO 09 — WILDCARD TLS + HTTPRoute / GRPCRoute / TCPRoute"
run "$K -n routes get gateway,httproute,grpcroute,tcproute"
run "$K -n routes get certificate"
CA=$(mktemp); $K -n cert-manager get secret clustermesh-root-ca -o jsonpath='{.data.tls\.crt}' 2>/dev/null | base64 -d > "$CA"
GW=$($K -n routes get gateway routes-gw -o jsonpath='{.status.addresses[0].value}' 2>/dev/null)
echo "HTTPS, chain-verified against the exported root (never -k). The wildcard covers a name with no cert of its own:"
run "for h in web.poc.local anything-at-all.poc.local exact.example.test hubble.poc.local; do printf '%-28s ' \$h; curl -s --max-time 8 --cacert $CA --resolve \$h:443:$GW https://\$h/ -o /dev/null -w '[http=%{http_code}]\\n'; done"
echo "NEGATIVE — a name no listener covers must fail the handshake (curl exit 35):"
run "curl -s --max-time 8 --cacert $CA --resolve nobody.example.test:443:$GW https://nobody.example.test/ -o /dev/null -w '[http=%{http_code}]\\n'; echo \"exit=\$?\""
run "docker run --rm --network kind fullstorydev/grpcurl:latest -plaintext -authority grpc.poc.local $GW:80 grpc.health.v1.Health/Check"
run "(echo 'ping from verify.sh'; sleep 1) | nc -w 5 $GW 9000"
# ALPN must be negotiated on the TLS listeners or current gRPC clients refuse them (gotcha #33).
run "for s in grpc.poc.local web.poc.local exact.example.test; do printf '%-20s ' \$s; echo | openssl s_client -connect $GW:443 -servername \$s -alpn h2,http/1.1 2>/dev/null | grep ALPN; done"
# The native client (demo 09 Part 11): all three routes from a current grpc-go, no Docker. Needs Go.
if command -v go >/dev/null 2>&1; then
  run "(cd demos/09-routes/app && go run . -mode client -target $GW -ca ../../../docs/root-ca.crt)"
else
  echo '(go not installed: skipping the native client; see demos/09-routes/README.md Part 11)'; echo
fi
rm -f "$CA"

hdr "11. DEMO 10 — HUBBLE FLOW EXPORT -> OTEL"
run "$K -n kube-system get cm cilium-flowlog-config -o jsonpath='{.data.flowlogs\\.yaml}' 2>/dev/null | grep -E 'name:|filePath:' "
run "for n in poc1-worker poc1-worker2; do printf '%-14s ' \$n; docker exec \$n sh -c 'ls -l /var/run/cilium/hubble/ 2>/dev/null | tail -n +2 | awk \"{print \\\$5, \\\$9}\" | tr \"\\n\" \"  \"'; echo; done"
run "$K -n otel get pods -o wide --no-headers 2>/dev/null | awk '{print \$1, \$2, \$3, \$7}'"
echo "Records emitted by one collector in the last 5 minutes:"
run "$K -n otel logs \$($K -n otel get pod -l app=otel-collector -o jsonpath='{.items[0].metadata.name}' 2>/dev/null) --since=5m 2>/dev/null | grep -c '^LogRecord #'"

hdr "13. DEMO 15 — THE BANK ACROSS THE MESH (global services, replication, one cross-cluster call)"
run "$K -n bank get pods -o wide --no-headers 2>/dev/null | awk '{print \$1, \$2, \$3, \$7}'"
run "kubectl --context kind-poc2 -n bank get pods -o wide --no-headers 2>/dev/null | awk '{print \$1, \$2, \$3, \$7}'"
echo "poc1's service map: accounts has a backend it never scheduled (poc2), payments one from each cluster:"
BANK_ACC=$($K -n bank get svc accounts -o jsonpath='{.spec.clusterIP}' 2>/dev/null); BANK_PAY=$($K -n bank get svc payments -o jsonpath='{.spec.clusterIP}' 2>/dev/null)
run "$K -n kube-system exec ds/cilium -c cilium-agent -- cilium-dbg service list 2>/dev/null | grep -E 'Frontend|$BANK_ACC:80|$BANK_PAY:80' -A2 | grep -E 'Frontend|=>|:80/TCP'"
echo "the database: primary in poc2 with a standby streaming from poc1 through the mesh:"
run "kubectl --context kind-poc2 -n bank exec postgres-0 -c postgres -- psql -U bank -d bank -Atc \"SELECT 'primary: in_recovery='||pg_is_in_recovery()||'  standby='||client_addr||' '||state||' lag='||coalesce(replay_lag::text,'0') FROM pg_stat_replication\""
run "$K -n bank exec postgres-standby-0 -c postgres -- psql -U bank -d bank -Atc \"SELECT 'standby: in_recovery='||pg_is_in_recovery()||' '||status||' from '||sender_host FROM pg_stat_wal_receiver\""
echo "one request through the Gateway, its path in the body — api in poc1, accounts (and the primary) in poc2:"
# docs/root-ca.crt (the committed public root), not section 10's temp file — that one is removed at the end of section 10.
run "curl -s --cacert docs/root-ca.crt --resolve bankapi.poc.local:443:$GW https://bankapi.poc.local/api/balance/chk-1001 | python3 -c 'import json,sys; d=json.load(sys.stdin); print({\"api\": d[\"served_by\"][\"cluster\"], \"accounts\": d[\"upstream\"][\"served_by\"][\"cluster\"], \"db\": d[\"upstream\"].get(\"db\"), \"balance_cents\": d[\"balance_cents\"]})'"

hdr "14. DEMO 16 — MONITORING (kube-prometheus-stack + Cilium/Hubble ServiceMonitors)"
run "$K -n monitoring get pods --no-headers 2>/dev/null | awk '{print \$1, \$2, \$3}'"
echo "Prometheus targets (via the API-server proxy — the Prometheus image has no shell tools):"
run "kubectl --context $CTX get --raw '/api/v1/namespaces/monitoring/services/monitoring-kube-prometheus-prometheus:9090/proxy/api/v1/targets?state=active' 2>/dev/null | python3 -c 'import json,sys; ts=json.load(sys.stdin)[\"data\"][\"activeTargets\"]; ks=sorted(set(t[\"scrapePool\"].split(\"/\")[2] for t in ts if \"/kube-system/\" in t[\"scrapePool\"])); print(\"total\", len(ts), \"up\", sum(1 for t in ts if t[\"health\"]==\"up\"), \"| cilium pools:\", ks)'"
echo "Hubble series with a cluster label, and the six chart dashboards Grafana loaded:"
run "kubectl --context $CTX get --raw '/api/v1/namespaces/monitoring/services/monitoring-kube-prometheus-prometheus:9090/proxy/api/v1/query?query=count%20by%20(cluster)%20(%7B__name__%3D~%22hubble_.%2B%22%7D)' 2>/dev/null | python3 -c 'import json,sys; [print(\"hubble series:\", r[\"value\"][1], \"cluster=\"+r[\"metric\"].get(\"cluster\",\"-\")) for r in json.load(sys.stdin)[\"data\"][\"result\"]]'"
run "curl -s --cacert docs/root-ca.crt --resolve grafana.poc.local:443:$GW -u admin:poc-grafana 'https://grafana.poc.local/api/search?type=dash-db' | python3 -c 'import json,sys; d=json.load(sys.stdin); print(len([x for x in d if \"ilium\" in x[\"title\"] or \"ubble\" in x[\"title\"]]), \"cilium/hubble dashboards of\", len(d))'"

hdr "15. DEMO 18 — OBI (zero-code traces, both clusters → one collector)"
run "for c in poc1 poc2; do kubectl --context kind-\$c -n obi get pods --no-headers 2>/dev/null | awk -v c=\$c '{print c, \$1, \$2, \$3}'; done"
echo "spans that reached the poc1 collector in the last 5 minutes, by originating cluster:"
run "for p in \$($K -n otel get pods -o name 2>/dev/null | cut -d/ -f2); do $K -n otel logs \$p --since=5m 2>/dev/null; done | grep 'k8s.cluster.name' | sort | uniq -c"

hdr "16. DEMO 19 — THE ZERO-TRUST CELL (clusterwide baseline + rendered policies, both clusters)"
run "for c in poc1 poc2; do echo \"-- \$c --\"; kubectl --context kind-\$c get ccnp --no-headers 2>/dev/null; kubectl --context kind-\$c -n bank get cnp --no-headers 2>/dev/null | awk '{print \$1}' | tr '\\n' ' '; echo; done"
echo "the rendering is reproducible from intent.yaml (no diff = what is committed is what render.py produces):"
run "demos/19-zero-trust-cell/render.py < demos/19-zero-trust-cell/intent.yaml | diff - demos/19-zero-trust-cell/rendered/cell-policies.yaml && echo 'rendered/cell-policies.yaml is current'"

hdr "17. DEMO 20 — SPRING BOOT (petclinic) IN springboot"
run "$K -n springboot get deploy -o custom-columns='DEPLOY:.metadata.name,READY:.status.readyReplicas,WANT:.spec.replicas' --no-headers 2>/dev/null"
echo "the API through the Gateway (needs the six JVMs up; 503 = none Ready):"
run "curl -s --cacert docs/root-ca.crt --resolve petclinic.poc.local:443:$GW -m 15 -o /dev/null -w 'GET /api/customer/owners -> %{http_code}\n' https://petclinic.poc.local/api/customer/owners"

hdr "18. DEMO 21 — TEMPO (exemplar trace ids resolve to stored traces)"
run "kubectl --context $CTX get --raw '/api/v1/namespaces/monitoring/services/tempo:3200/proxy/ready' 2>/dev/null; echo"
echo "one Hubble exemplar trace id from the last hour, looked up in Tempo:"
run "ID=\$(kubectl --context $CTX get --raw \"/api/v1/namespaces/monitoring/services/monitoring-kube-prometheus-prometheus:9090/proxy/api/v1/query_exemplars?query=hubble_http_request_duration_seconds_bucket&start=\$(( \$(date +%s) - 3600 ))&end=\$(date +%s)\" 2>/dev/null | python3 -c 'import json,sys; d=json.load(sys.stdin)[\"data\"]; print(next((e[\"labels\"][\"traceID\"] for x in d for e in x[\"exemplars\"]), \"\"))'); echo \"exemplar traceID: \${ID:-none}\"; [ -n \"\$ID\" ] && kubectl --context $CTX get --raw \"/api/v1/namespaces/monitoring/services/tempo:3200/proxy/api/traces/\$ID\" 2>/dev/null | python3 -c 'import json,sys; d=json.load(sys.stdin); b=d.get(\"batches\") or []; print(\"in Tempo:\", sum(len(ss.get(\"spans\",[])) for rs in b for ss in rs.get(\"scopeSpans\",[])), \"spans\")'"

hdr "19. DEMO 22 — poc2 → the hub (remote write across the mesh)"
run "kubectl --context $CTX get --raw '/api/v1/namespaces/monitoring/services/monitoring-kube-prometheus-prometheus:9090/proxy/api/v1/query?query=count%20by%20(cluster)%20(up)' 2>/dev/null | python3 -c 'import json,sys; [print(\"cluster=%s up-series=%s\" % (r[\"metric\"].get(\"cluster\",\"-\"), r[\"value\"][1])) for r in json.load(sys.stdin)[\"data\"][\"result\"]]'"
run "kubectl --context $CTX get --raw '/api/v1/namespaces/monitoring/services/monitoring-kube-prometheus-prometheus:9090/proxy/api/v1/query?query=time()%20-%20max(timestamp(up%7Bcluster%3D%22poc2%22%7D))' 2>/dev/null | python3 -c 'import json,sys; r=json.load(sys.stdin)[\"data\"][\"result\"]; print(\"newest poc2 sample: %.0f s old\" % float(r[0][\"value\"][1]) if r else \"no poc2 samples\")'"

hdr "20. DEMO 23 — the collector is a per-cluster service (local backends only)"
run "for C in poc1 poc2; do IP=\$(kubectl --context kind-\$C -n otel get svc otel-collector -o jsonpath='{.spec.clusterIP}'); AG=\$(kubectl --context kind-\$C -n kube-system get pods -l k8s-app=cilium --field-selector spec.nodeName=\$C-worker -o name | head -1); N=\$(kubectl --context kind-\$C -n kube-system exec \$AG -c cilium-agent -- cilium-dbg service list 2>/dev/null | awk -v ip=\"\$IP:4318/TCP\" '\$1 ~ /^[0-9]+\$/ && \$2 ~ /\\/TCP\$/ {p=(\$2==ip)} p && /=>/ {n++} END{print n+0}'); L=\$(kubectl --context kind-\$C -n otel get pods -l app=otel-collector --field-selector status.phase=Running --no-headers | wc -l | tr -d ' '); echo \"\$C: otel-collector backends=\$N local collector pods=\$L global=[\$(kubectl --context kind-\$C -n otel get svc otel-collector -o jsonpath='{.metadata.annotations.service\\.cilium\\.io/global}')]\"; done"

hdr "21. DEMO 24 — one root for the mesh AND Hubble; relay sees every node"
run "for C in poc1 poc2; do echo \"\$C: hubble-server-certs \$(kubectl --context kind-\$C -n kube-system get secret hubble-server-certs -o jsonpath='{.data.tls\\.crt}' | base64 -d | openssl x509 -noout -issuer | sed 's/issuer=//')  certificates ready \$(kubectl --context kind-\$C -n kube-system get certificates -o jsonpath='{range .items[*]}{.status.conditions[?(@.type==\"Ready\")].status}{\"\\n\"}{end}' | grep -c True)/\$(kubectl --context kind-\$C -n kube-system get certificates -o name | wc -l | tr -d ' ')\"; done"
run "kubectl --context $CTX -n kube-system port-forward svc/hubble-relay 4245:443 >/dev/null 2>&1 & PF=\$!; sleep 3; hubble status --server localhost:4245 \$(scripts/hubble-tls.sh $CTX) 2>/dev/null | grep -E 'Connected Nodes|Unavailable'; kill \$PF"

hdr "22. DEMO 25 — hubble-observer → Loki: the pipeline is up and flows are stored"
run "kubectl --context $CTX -n hubble-observer get pods -o custom-columns='POD:.metadata.name,READY:.status.containerStatuses[0].ready,RESTARTS:.status.containerStatuses[0].restartCount' --no-headers; kubectl --context $CTX -n monitoring get pods -l app.kubernetes.io/name=loki -o custom-columns='POD:.metadata.name,READY:.status.containerStatuses[*].ready' --no-headers"
run "kubectl --context $CTX get --raw '/api/v1/namespaces/monitoring/services/loki:3100/proxy/loki/api/v1/query?query=sum%20by%20(flow_source_cluster_name)%20(count_over_time(%7Bnamespace%3D%22hubble-observer%22%2Ccontainer%3D%22hubble-observer%22%7D%20%7C%20json%20%7C%20__error__%3D%22%22%20%5B24h%5D))' 2>/dev/null | python3 -c 'import json,sys; r=json.load(sys.stdin)[\"data\"][\"result\"]; print(\"stored DROPPED flows, 24 h, by source cluster:\", {x[\"metric\"].get(\"flow_source_cluster_name\",\"-\"): x[\"value\"][1] for x in r} if r else \"none\")'"

hdr "12. HOST ROUTING (macOS)"
run "netstat -rn -f inet | grep '^172.18' || echo 'no route — see SETUP Step 3.5'"
run "ifconfig -l | tr ' ' '\n' | grep -E '^bridge'"

echo
echo "---"
echo
echo "_End of run. Nothing above is transcribed by hand; re-run \`scripts/verify.sh\` to regenerate._"
