#!/usr/bin/env bash
# verify.sh — run every claim this PoC makes, end to end, and print the real output.
#
# Usage:
#   scripts/verify.sh                      # print to the terminal
#   scripts/verify.sh > docs/VERIFICATION_RUN.md   # capture it as a document
#
# WHY THIS EXISTS. Every README quotes captured output, but quoted output goes stale the moment
# something changes. This script re-runs all of it in one pass, so a reader can regenerate the
# evidence on their own cluster and compare, rather than trusting a snapshot from someone else's
# laptop.
#
# It is READ-ONLY apart from the HTTP requests it makes to the demo app, which is itself a
# read-only workload. It creates nothing and deletes nothing.
#
# Exit code is always 0: this is an evidence report, not a pass/fail gate. Some commands are
# EXPECTED to fail (a curl that times out is how an L3 policy denial looks), so a non-zero exit
# would be misleading. Read the output.
set -uo pipefail

CTX="${CTX:-kind-poc1}"
K="kubectl --context $CTX"

hdr() {
  echo
  echo '```'
  echo "════════════════════════════════════════════════════════════════════════════════"
  echo " $*"
  echo "════════════════════════════════════════════════════════════════════════════════"
  echo '```'
  echo
}
run() {
  echo '```console'
  echo "\$ $*"
  eval "$@" 2>&1
  rc=$?
  [ $rc -ne 0 ] && echo "[exit code: $rc]"
  echo '```'
  echo
}

echo "# Verification run"
echo
echo "Generated by \`scripts/verify.sh\` on **$(date -u +%Y-%m-%dT%H:%M:%SZ)** against context \`$CTX\`."
echo
echo "Every block below is a real command and its real output. Re-run the script to regenerate."

hdr "0. VERSIONS"
run "kind --version"
run "$K version --client -o yaml | grep gitVersion | head -1"
run "helm version --short"
run "cilium version --client | head -1"
run "hubble version"
run "docker info --format 'Mem={{.MemTotal}} CPUs={{.NCPU}} Kernel={{.KernelVersion}}'"

hdr "1. CLUSTER STATE"
run "$K get nodes -o wide"
run "$K get pods -A -o wide"

hdr "2. CILIUM STATUS"
run "$K -n kube-system exec ds/cilium -c cilium-agent -- cilium-dbg status"
echo "The \`Degraded(1)\` in Modules Health is a known kernel constraint, not a fault — see docs/FINDINGS.md:"
run "$K -n kube-system exec ds/cilium -c cilium-agent -- cilium-dbg status --all-health 2>/dev/null | grep -A2 socket-termination"

hdr "3. DEMO 03 — SERVICES WITHOUT KUBE-PROXY"
echo "Only Cilium's own DaemonSets exist — no kube-proxy:"
run "$K -n kube-system get daemonset"
echo "Zero Service iptables chains. A kube-proxy cluster would have dozens:"
run "docker exec poc1-worker sh -c 'iptables-save 2>/dev/null | grep -c KUBE-SVC || echo 0'"
echo "What is doing the load balancing instead — note entry for 10.11.0.1:443, the API itself:"
run "$K -n kube-system exec ds/cilium -c cilium-agent -- cilium-dbg service list 2>/dev/null | head -14"

hdr "4. DEMO 02 — L3/L4 vs L7 NETWORK POLICY"
run "$K get ciliumnetworkpolicy"
echo "Allowed by the L7 rule:"
run "$K exec tiefighter -- curl -s -XPOST -w '\n[http_code=%{http_code} time=%{time_total}s]\n' --max-time 8 deathstar.default.svc.cluster.local/v1/request-landing"
echo "SAME pod, SAME port, different method+path — refused at L7 with an immediate 403:"
run "$K exec tiefighter -- curl -s -XPUT -w '\n[http_code=%{http_code} time=%{time_total}s]\n' --max-time 8 deathstar.default.svc.cluster.local/v1/exhaust-port"
echo "Denied at L3/L4 instead — the SYN is dropped, so this TIMES OUT rather than returning 403:"
run "$K exec xwing -- curl -s -XPOST -w '\n[http_code=%{http_code}]\n' --max-time 6 deathstar.default.svc.cluster.local/v1/request-landing"

hdr "5. DEMO 05 — GATEWAY API + LB IPAM (no kube-vip, no MetalLB)"
run "$K get gatewayclass"
run "$K get gateway,httproute"
run "$K get svc -A --field-selector spec.type=LoadBalancer"
run "$K describe ciliumloadbalancerippool kind-docker-pool | sed -n '1,20p'"
echo "Which node is announcing each address (leader-elected, like kube-vip would do):"
run "$K -n kube-system get lease | grep l2announce"
echo "Proof nothing else is installed:"
run "$K get pods -A | grep -iE 'kube-vip|metallb' || echo 'none — no kube-vip, no MetalLB'"
echo "From the macOS host, through the Gateway (needs the SETUP Step 3.5 route):"
run "curl -s -XPOST -w '\n[http_code=%{http_code} time=%{time_total}s]\n' --max-time 8 http://172.18.255.200/v1/request-landing"
echo "Policy still applies to Gateway traffic — the dangerous path is refused here too:"
run "curl -s -XPUT -w '\n[http_code=%{http_code} time=%{time_total}s]\n' --max-time 8 http://172.18.255.200/v1/exhaust-port"
run "curl -s -o /dev/null -w 'hubble-ui http://172.18.255.201/ -> [http_code=%{http_code} time=%{time_total}s]\n' --max-time 8 http://172.18.255.201/"

hdr "6. DEMO 04 — WIREGUARD TRANSPARENT ENCRYPTION"
echo "Encryption status per node — distinct pubkeys, 4 peers each:"
for n in poc1-worker poc1-worker2 poc1-control-plane poc1-control-plane2 poc1-control-plane3; do
  POD=$($K -n kube-system get pod -l k8s-app=cilium --field-selector "spec.nodeName=$n" -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)
  echo '```console'
  echo "\$ cilium-dbg status | grep Encryption   # on $n"
  $K -n kube-system exec "$POD" -c cilium-agent -- cilium-dbg status 2>/dev/null | grep -i '^Encryption' || echo "(unavailable)"
  echo '```'
  echo
done
echo "The device, and its counters — proof it is carrying real traffic:"
run "docker exec poc1-worker ip -s link show cilium_wg0"

hdr "7. DEMO 01 — HUBBLE OBSERVABILITY"
run "hubble status -P 2>&1 | grep -v level=WARN"
echo "L7 flows, with method, path, status and latency — no application instrumentation:"
run "hubble observe --last 6 -P --protocol http 2>&1 | grep -v level=WARN"
echo "Verdicts. Note the two shapes: 'Policy denied ... SYN' is L3/L4, 'http-request DROPPED' is L7:"
run "hubble observe --last 6 -P --verdict DROPPED 2>&1 | grep -v level=WARN"

hdr "8. HOST ROUTING (macOS)"
run "netstat -rn -f inet | grep '^172.18' || echo 'no route — see SETUP Step 3.5'"
run "ifconfig -l | tr ' ' '\n' | grep -E '^bridge'"

echo
echo "---"
echo
echo "_End of run. Nothing above is transcribed by hand; re-run \`scripts/verify.sh\` to regenerate._"
