frr defaults traditional
hostname leaf2
log stdout
!
interface lo
 ip address 10.200.255.12/32
!
router bgp 65102
 bgp router-id 10.200.255.12
 maximum-paths 8
 neighbor 10.200.1.11 remote-as 65100
 neighbor 10.200.1.11 description spine
 neighbor 10.200.1.11 password ${FABRIC_BGP_PASSWORD}
 neighbor 10.200.1.11 timers 3 9
 neighbor 10.200.1.11 soft-reconfiguration inbound
 neighbor 10.200.1.11 route-map FABRIC-IN in
 neighbor 10.200.1.11 route-map LEAF-OUT out
 neighbor 10.200.1.11 maximum-prefix 256
 neighbor SERVERS peer-group
 neighbor SERVERS remote-as external
 neighbor SERVERS password ${FABRIC_BGP_PASSWORD}
 neighbor SERVERS soft-reconfiguration inbound
 neighbor SERVERS route-map SERVERS-IN in
 neighbor SERVERS route-map NOTHING out
 neighbor SERVERS maximum-prefix 64
 neighbor SERVERS timers 3 9
 bgp listen range 172.19.0.0/17 peer-group SERVERS
 bgp listen range 172.18.0.0/17 peer-group SERVERS
 bgp listen limit 16
 network 10.200.255.12/32
 bgp as-path access-list EG-POC1 seq 5 permit ^65021$
 bgp as-path access-list EG-POC2 seq 5 permit ^65022$
 bgp as-path access-list CILIUM-POC1 seq 5 permit ^65001$
 bgp as-path access-list CILIUM-POC2 seq 5 permit ^65002$
!
ip prefix-list COMPANY seq 10 permit 10.200.0.0/16 le 32
ip prefix-list EG-VIPS seq 10 permit 10.98.0.0/24 ge 32 le 32
ip prefix-list CILIUM-VIPS seq 10 permit 10.99.0.0/24 ge 32 le 32
ip prefix-list EG-POC1-VIPS seq 10 permit 10.98.0.0/26 ge 32 le 32
ip prefix-list EG-POC2-VIPS seq 10 permit 10.98.0.64/26 ge 32 le 32
ip prefix-list EG-ANYCAST-VIPS seq 10 permit 10.98.0.192/26 ge 32 le 32
ip prefix-list CILIUM-POC1-VIPS seq 10 permit 10.99.0.0/26 ge 32 le 32
ip prefix-list CILIUM-POC2-VIPS seq 10 permit 10.99.0.64/26 ge 32 le 32
ip prefix-list CILIUM-ANYCAST-VIPS seq 10 permit 10.99.0.192/26 ge 32 le 32
!
route-map SERVERS-IN permit 10
 match ip address prefix-list EG-POC1-VIPS
 match as-path EG-POC1
route-map SERVERS-IN permit 20
 match ip address prefix-list EG-POC2-VIPS
 match as-path EG-POC2
route-map SERVERS-IN permit 30
 match ip address prefix-list EG-ANYCAST-VIPS
 match as-path EG-POC1
route-map SERVERS-IN permit 31
 match ip address prefix-list EG-ANYCAST-VIPS
 match as-path EG-POC2
route-map SERVERS-IN permit 40
 match ip address prefix-list CILIUM-POC1-VIPS
 match as-path CILIUM-POC1
route-map SERVERS-IN permit 50
 match ip address prefix-list CILIUM-POC2-VIPS
 match as-path CILIUM-POC2
route-map SERVERS-IN permit 60
 match ip address prefix-list CILIUM-ANYCAST-VIPS
 match as-path CILIUM-POC1
route-map SERVERS-IN permit 61
 match ip address prefix-list CILIUM-ANYCAST-VIPS
 match as-path CILIUM-POC2
!
route-map NOTHING deny 10
!
route-map LEAF-OUT permit 10
 match ip address prefix-list COMPANY
route-map LEAF-OUT permit 20
 match ip address prefix-list EG-VIPS
route-map LEAF-OUT permit 30
 match ip address prefix-list CILIUM-VIPS
!
route-map FABRIC-IN permit 10
 match ip address prefix-list COMPANY
route-map FABRIC-IN permit 20
 match ip address prefix-list EG-VIPS
route-map FABRIC-IN permit 30
 match ip address prefix-list CILIUM-VIPS
!
