apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: pos
  namespace: cf2cnp-lab
  labels:
    app.kubernetes.io/managed-by: cf2cnp
    app.kubernetes.io/name: pos
spec:
  description: 'Allow egress from pos in cf2cnp-lab: to shop on TCP/80; to example.com on TCP/443; to kube-dns in kube-system on ANY/53 (DNS *)'
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: pos
  egress:
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: shop
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
    - toFQDNs:
        - matchName: example.com
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: '*'
